-- Order and OrderItem tables. Schema is owned by Flyway; Hibernate only validates.
CREATE TABLE orders (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_reference VARCHAR(100) NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL
);

CREATE TABLE order_items (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT        NOT NULL,
    product_sku VARCHAR(64)   NOT NULL,
    quantity    INTEGER       NOT NULL,
    unit_price  NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
