-- Product table + idempotency-key store. Schema is owned by Flyway; Hibernate validates.
CREATE TABLE products (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    sku         VARCHAR(64)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12,2) NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    version     BIGINT        NOT NULL,
    CONSTRAINT uq_products_sku UNIQUE (sku)
);

CREATE INDEX idx_products_status ON products (status);
CREATE INDEX idx_products_name ON products (name);

CREATE TABLE idempotency_keys (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    product_id      BIGINT       NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    CONSTRAINT fk_idempotency_product FOREIGN KEY (product_id) REFERENCES products (id)
);
