-- Category and Product tables. Schema is owned by Flyway; Hibernate only validates.
CREATE TABLE categories (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    version    BIGINT       NOT NULL,
    CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE products (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200)  NOT NULL,
    sku         VARCHAR(64)   NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12,2) NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    category_id BIGINT        NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    version     BIGINT        NOT NULL,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_status ON products (status);
