-- Customer table. Schema is owned by Flyway; Hibernate only validates against it.
CREATE TABLE customers (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(320) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_customers_email UNIQUE (email)
);
